global:
  scrape_interval: 30s
  scrape_timeout: 10s

#rule_files:
#  - alert.yml

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets:
          - '127.0.0.1:9090'

  - job_name: 'user-srvc'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']