spring:
  application:
    name: user-srvc
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

server:
  connection-timeout: 30s
  tomcat:
    threads:
      max: 2

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, prometheus, metrics
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true